title: My Website
description: My portfolio and blog
baseurl: "" # leave blank unless your site is in a subfolder
markdown: kramdown
url: "https://techondemand.ca"


theme: minima # built-in Jekyll theme
plugins:
  - jekyll-feed